### ISSUE TITLE
No such file or directory:'./debug_tools/'

### ISSUE THREAD

**Issue by cosmosmosco** [cassiePython/NeRF-Art#10]
Hi, when I run train.py, there was a FileNotFound error. I didn't find this file in the folder.
Is this debug_tools important? Can I remove it from subdirs_to_copy?
Traceback (most recent call last):
  File "/media/xxl/data/projects/NeRF-Art-main/train.py", line 343, in <module>
    main_function(config)
  File "/media/xxl/data/projects/NeRF-Art-main/train.py", line 73, in main_function
    io_util.backup(os.path.join(exp_dir, 'backup'))
  File "/media/xxl/data/projects/NeRF-Art-main/utils/io_util.py", line 99, in backup
    files = os.listdir(os.path.join(this_dir, subdir))
FileNotFoundError: [Errno 2] No such file or directory: './debug_tools/'

**Comment by cassiePython** [comment]
Actually, this directory has not been used, you can directly create this directory to avoid this error: mkdir debug_tools
